src/RantApp/RantApp.UI/Controllers/HomeController.cs
using RantApp.BLL.Interfaces;
using RantApp.BLL.Models;
using RantApp.BLL.ViewModels;
using RantApp.DAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RantApp.UI.Controllers
{
    public class HomeController : Controller
    {
        private static IReadWriteRepository<Rant> _repository = new RantRepository();

        // GET: Rant
        public ActionResult Index()
        {
            RantViewModel viewModel = new RantViewModel(_repository);
            viewModel.Rants = viewModel.GetRants()
                .OrderByDescending(r => r.PostDate)
                .ThenBy(r => r.Title)
                .ToList();

            return View(viewModel);
        }
    }
}

src/RantApp/RantApp.UI/Controllers/RantController.cs
using System.Web.Mvc;
using RantApp.BLL.ViewModels;
using RantApp.BLL.Interfaces;
using RantApp.DAL.Repositories;
using RantApp.BLL.Models;
using System.Net;
using System;
using System.Linq;
using System.Collections.Generic;

namespace RantApp.UI.Controllers
{
    public class RantController : Controller
    {
        private static IReadWriteRepository<Rant> _rantRepository = new RantRepository();
        private static IReadRepository<Emotion> _emotionRepository = new EmotionRepository();

        public ViewResult Create()
        {
            RantViewModel viewModel = new RantViewModel(_rantRepository, _emotionRepository);
            return View(viewModel);
        }

        public PartialViewResult _WizardTitleScreen(RantViewModel viewModel)
        {
            if (viewModel == null)
                viewModel = new RantViewModel(_rantRepository, _emotionRepository);

            if (viewModel != null)
            {
                if (viewModel.CurrentRant == null)
                    viewModel.CurrentRant = new Rant();

                TempData["emotionItems"] = viewModel.Emotions.EmotionItems;

                return PartialView("_WizardTitleScreen", viewModel);
            }

            return PartialView(this);
        }

        // Wizard Action Methods
        [HttpPost]
        public PartialViewResult _WizardTitleScreen(RantViewModel viewModel, string prevBtn, string nextBtn)
        {
            if (nextBtn != null && ModelState.IsValid)
            {
                Rant modelRant = viewModel.CurrentRant;

                if (modelRant == null)
                {
                    return PartialView(viewModel);
                }

                Rant newRant = GetRantSession();
                newRant.EmotionId = viewModel.Emotions.SelectedItemId;
                viewModel.Emotions.EmotionItems = (List<SelectListItem>)TempData["emotionItems"];

                string emotionType = viewModel.Emotions.EmotionItems.FirstOrDefault(
                    e => e.Value == newRant.EmotionId.ToString()).Text;

                newRant.Title = string.Format("I'm {0} {1}", emotionType, modelRant.Title);

                return PartialView("_WizardTellUsMoreScreen", viewModel);
            }

            return PartialView();
        }

        [HttpPost]
        public ActionResult _WizardTellUsMoreScreen(RantViewModel viewModel,
            string prevBtn, string nextBtn)
        {
            Rant newRant = GetRantSession();

            if (prevBtn != null)
            {
                if (viewModel.CurrentRant == null)
                    viewModel.CurrentRant = new Rant();

                TempData["emotionItems"] = viewModel.Emotions.EmotionItems;

                return View("Create", viewModel);
            }

            if (nextBtn != null && ModelState.IsValid)
            {
                Rant modelRant = viewModel.CurrentRant;

                if (modelRant == null)
                {
                    return PartialView(viewModel);
                }

                newRant.Description = viewModel.CurrentRant.Description;

                return PartialView("_WizardReactionTypeExpectedScreen", viewModel);
            }

            return PartialView(this);
        }

        [HttpPost]
        public ActionResult _WizardReactionTypeExpectedScreen(RantViewModel viewModel,
            string prevBtn, string nextBtn)
        {
            Rant newRant = GetRantSession();

            if (prevBtn != null)
            {
                if (viewModel.CurrentRant == null)
                    viewModel.CurrentRant = new Rant();

                return View("Create", viewModel);
            }

            if (nextBtn != null && ModelState.IsValid)
            {
                Rant modelRant = viewModel.CurrentRant;

                if (modelRant == null)
                {
                    return PartialView(viewModel);
                }

                newRant.ExpectedReactionRequest = viewModel.CurrentRant.ExpectedReactionRequest;

                return RedirectToAction("_WizardSummary", viewModel);
            }

            return PartialView(this);
        }

        public PartialViewResult _WizardSummary(RantViewModel viewModel)
        {
            if (viewModel == null)
                viewModel = new RantViewModel(_rantRepository, _emotionRepository);

            if (viewModel != null)
            {
                viewModel.CurrentRant = GetRantSession();
                return PartialView("_WizardSummary", viewModel);
            }

            return PartialView(this);
        }

        [HttpPost]
        public ActionResult _WizardSummary(RantViewModel viewModel, string prevBtn, string doneBtn)
        {
            if (prevBtn != null)
            {
                // TODO: Redirect
                return null;
            }

            if (doneBtn != null && ModelState.IsValid)
            {
                viewModel.CurrentRant = GetRantSession();
                viewModel.CurrentRant.PostDate = DateTime.Now.ToLocalTime();
                viewModel.SaveRant(viewModel.CurrentRant);
                return RedirectToAction("Index", "Home");
            }

            // TOOD
            return null;
        }

        public ActionResult Details(int? id)
        {
            RantViewModel viewModel = new RantViewModel(_rantRepository);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                Rant rant = viewModel.GetRantById((int)id);
                return View(rant);
            }

            return RedirectToAction("Index");
        }

        private Rant GetRantSession()
        {
            if (Session["rant"] == null)
            {
                Session["rant"] = new Rant();
            }
            return (Rant)Session["rant"];
        }
    }
}

src/RantApp/RantApp.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/RantApp/RantApp.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/RantApp/RantApp.UI/Views/Home/Index.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Rants</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Rant")
</p>
<table class="table">
    <tr>
        <th>What people are talking about?</th>
        <th>Posted on</th>
    </tr>

    @foreach (var item in Model.Rants)
    {
        <tr>
            <td><a href="@Url.Action("Details", "Rant", new { id = item.RantId })">@item.Title</a></td>
            <td>@item.PostDate</td>
            <td>
                @Html.ActionLink("View", "Details", "Rant", new { id = item.RantId })
            </td>
        </tr>
    }

</table>

src/RantApp/RantApp.UI/Views/Rant/Create.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

@{
    ViewBag.Title = "Create New Rant";
}

<h2>Ready to Rant?</h2>


@*@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    
}*@

<div class="form-horizontal">
    <h4>Tell us how you feel. Share your thoughts, emotions, and opinions with the world.</h4>
    <hr />
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    <!--<div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>-->

    <div id="wizard-views">
        @Html.Action("_WizardTitleScreen", Model)
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/RantApp/RantApp.UI/Views/Rant/Details.cshtml
@model RantApp.BLL.Models.Rant

@{
    ViewBag.Title = Model.Title;
}

<!--Add user photo and username here-->

<div>
    <h2>@Html.DisplayFor(m => m.Title)</h2>
    <h6>Posted on @Html.DisplayFor(m => m.PostDate)</h6>
    <hr />
    <p>@Html.DisplayFor(m => m.Description)</p>
    <hr />

    <div class="reactions">
        <h3>Here's how people reacted:</h3>
        @foreach (var item in Model.Reactions)
        {
            <em><strong>@item.Title</strong></em>
            <p>@item.Response</p>
            <p>Reacted on: @item.PostDate</p>
            <hr/>
        }
    </div>
</div>
<p>
    @Html.ActionLink("Back to Rants", "Index", "Home")
</p>

src/RantApp/RantApp.UI/Views/Rant/Index.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Rants</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>What people are talking about?</th>
        <th>Posted on</th>
    </tr>

@foreach (var item in Model.Rants) {
    <tr>
        <td><a href="@Url.Action("Details", "Rant", new { id = item.RantId })">@item.Title</a></td>
        <td>@item.PostDate</td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })
            @Html.ActionLink("View", "Details", new { id = item.RantId })
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

src/RantApp/RantApp.UI/Views/Rant/_WizardReactionTypeExpectedScreen.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

@Html.ValidationSummary(false, "Please correct the following errors and try again.", new { @class = "text-danger" })

@using (Ajax.BeginForm("_WizardReactionTypeExpectedScreen", "Rant", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "wizard-views" }))
{
    <div class="form-fields">
        @Html.LabelFor(m => m.CurrentRant.ExpectedReactionRequest, "How do you want people to respond to this?")
        @Html.TextAreaFor(m => m.CurrentRant.ExpectedReactionRequest, new { style = "width: 33%" })
    </div>
    <br />
    <input type="submit" name="previousBtn" value="Previous" />
    <input type="submit" name="nextBtn" value="Next" />
}

src/RantApp/RantApp.UI/Views/Rant/_WizardSummary.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

<h2>Your New Rant</h2>
<p>Please see a summary of your rant below. You can click "Previous" to edit your rant before submitting.</p>

@using (Ajax.BeginForm("_WizardSummary", "Rant", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "wizard-views" }))
{
    <div class="rant-summary">
        <h4>What you are ranting about:</h4>
        @Html.DisplayFor(m => m.CurrentRant.Title)
        <hr />
        <h4>Rant Details:</h4>
        @Html.DisplayFor(m => m.CurrentRant.Description)
        <hr />
        <h4>How you expect your peers to respond:</h4>
        @Html.DisplayFor(m => m.CurrentRant.ExpectedReactionRequest)
    </div>

    <p>If you are ready for the world to see your rant, click "DONE" below.</p>
    <input type="submit" name="previousBtn" value="Previous" />
    <input type="submit" name="doneBtn" value="DONE" />
}

src/RantApp/RantApp.UI/Views/Rant/_WizardTellUsMoreScreen.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

@Html.ValidationSummary(false, "Please correct the following errors and try again.", new { @class = "text-danger" })

@using (Ajax.BeginForm("_WizardTellUsMoreScreen", "Rant", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "wizard-views" }))
{
    <div class="form-fields">
        @Html.LabelFor(m => m.CurrentRant.Description, "Tell us more about it.")
        @Html.TextAreaFor(m => m.CurrentRant.Description, new { style = "width: 33%" })
    </div>
    <br />
    <input type="submit" name="previousBtn" value="Previous" />
    <input type="submit" name="nextBtn" value="Next" />
}

src/RantApp/RantApp.UI/Views/Rant/_WizardTitleScreen.cshtml
@model RantApp.BLL.ViewModels.RantViewModel

@using (Ajax.BeginForm("_WizardTitleScreen", "Rant", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "wizard-views" }))
{
    @Html.ValidationSummary("Please correct the following errors and try again.", new { @class = "text-danger" })

    <div class="form-fields">
        <p>I'm @Html.DropDownListFor(
    m => m.Emotions.SelectedItemId,
    Model.Emotions.EmotionItems, "Select your emotion...", new { id = "selected-item-id" })
        @Html.TextBoxFor(m => m.CurrentRant.Title, new { id = "rant-title" })</p>
    </div>
    <br/>
    <input c" type="submit" name="nextBtn" value='Next' />
}

src/RantApp/RantApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Rants", "Index", "Rant")</li>
                    <!--<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>-->
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>